### ISSUE TITLE
src directory not published on npm

### ISSUE THREAD

**Issue by johnyb** [mzgol/grunt-check-dependencies#11]
I just updated to 0.11.1 and the task is now failing with:

```
Loading "check-dependencies.js" tasks...ERROR
>> Error: Cannot find module '../dist/src/check-dependencies'
Warning: Task "checkDependencies:dev" not found. Use --force to continue.
```

I looked into `node_module/grunt-check-dependencies/`, and there is now `src` directory. Seems it did not get published to npm.

**Comment by mzgol** [comment]
Oops! Thanks for the quick report, could you check if `0.11.2` (just published) is fine?

Unfortunately `npm test` works on built files so I can't detect issues like that automatically on Travis...

**Comment by johnyb** [comment]
Works fine now, thanks for the quick fix! :)
