### ISSUE TITLE
Parameter 'packageManager' doesn't work.

### ISSUE THREAD

**Issue by heytitle** [mzgol/grunt-check-dependencies#6]
My configuration:
```
checkDependencies: {
    packageManager: 'bower'
}
```

**Comment by heytitle** [comment]
Sorry, it's my false. The configuration should be something like this
```
checkDependencies: {
    main: {
        options: {
             packageManager: 'bower'
        }
    }
}
```

By the way, thank you for creating such useful plugin. :+1:

**Comment by mzgol** [comment]
Yeah, that's what Grunt multitasks require.

BTW, in the future please close an issue if you discover it's not valid after reporting. :) I'll do it myself here.

**Comment by heytitle** [comment]
Thanks
