### ISSUE TITLE
`onlySpecified` errors with scoped packages

### ISSUE THREAD

**Issue by Page-** [mzgol/grunt-check-dependencies#9]
The npm registry supports scoped packages in the form `@user/package` now, however with `onlySpecified` enabled it errors with `Package @user installed, though it shouldn't be`

**Comment by mzgol** [comment]
Fixed in mzgol/check-dependencies@11edefc, thanks for reporting. I have a Windows-related issue:
http://help.appveyor.com/discussions/problems/2532-invalid-npm-config-on-iojs-2-images
so I'll wait with publishing a little.

**Comment by mzgol** [comment]
`check-dependencies` 0.9.4 published; if you reinstall `grunt-check-dependencies` you'll get it.
